import Link from "next/link";

const steps = [
  { number: "01", track: "AI TRADING DESK", title: "Start with an event", body: "Frame a company or market question. Supply supported public sources or paste passages in Pro, then inspect every displayed claim beside its matched quote.", href: "/research", action: "Open Research Desk" },
  { number: "02", track: "TOKENIZED EQUITIES", title: "Map the exposure", body: "Review the linked Bitget Reality instrument, public market mark, freshness, and upside, downside, and invalidation scenarios. Choose whether to replay or monitor it.", href: "/markets", action: "Explore Market Map" },
  { number: "03", track: "ALPHA FACTORY", title: "Challenge the rule", body: "Run deterministic SMA research on completed public candles. Inspect the fixed holdout, rolling windows, cost stress, trades, and exact input fingerprint. Negative results stay visible.", href: "/strategies", action: "Open Strategy Lab" },
  { number: "04", track: "AGENTIC TRADING", title: "Observe in a paper ledger", body: "Nightwatch supports manual checks and an opt-in daily scheduled check on one Reality market. It records the decision and market snapshot, applies database-enforced limits before simulated fills, and remains pauseable by the account owner.", href: "/nightwatch", action: "Open Nightwatch" },
];

export default function DemoPage() {
  return <div className="content-wrap inner-page demo-page">
    <header className="page-heading demo-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> TIDELIGHT / THE PRODUCT WALKTHROUGH</div><h1>One event.<br/><span>A decision you can inspect.</span></h1><p>Follow the evidence from the first question to a guarded paper decision. Each step links to a working product surface and leaves the next action with the researcher.</p></div><div className="heading-note"><span className="note-star">✳</span><b>See the signal between sessions.</b><small>Three hackathon tracks, one traceable workflow.</small></div></header>
    <section className="demo-flow" aria-label="Tidelight guided walkthrough">{steps.map((step) => <article key={step.number}><div className="demo-step-index">{step.number}<span/></div><div className="demo-step-copy"><span className="eyebrow small-eyebrow">{step.track}</span><h2>{step.title}</h2><p>{step.body}</p><Link href={step.href}>{step.action} <span>↗</span></Link></div></article>)}</section>
    <section className="demo-architecture"><div><span className="eyebrow small-eyebrow">WHAT RUNS WHERE</span><h2>Small, explicit trust boundaries.</h2><p>Public Bitget endpoints provide market data. Server-side Qwen synthesis receives bounded source text. Supabase stores signed-in user records under row-level policies. The browser never receives provider secrets. Nightwatch is paper-only; Hobby deployments run the scheduled check once daily.</p></div><div className="architecture-layers"><div><b>Researcher</b><small>Question · selected sources · explicit handoffs</small></div><i>↓</i><div><b>Tidelight application</b><small>Quote checks · deterministic backtests · paper guardrails</small></div><i>↓</i><div><b>Providers & private ledger</b><small>Bitget public feed · Qwen server key · Supabase owner-scoped data</small></div></div></section>
    <section className="demo-proof-grid"><article><span>01 / RESEARCH</span><b>What can be checked now</b><p>Captured excerpts, quote-matched claims, source URLs, retrieval timestamps, and counter-evidence found in submitted passages.</p></article><article><span>02 / VALIDATION</span><b>What can be reproduced</b><p>Completed candle arrays, deterministic SMA 20/50 logic, explicit fee and slippage assumptions, windows, and hashes.</p></article><article><span>03 / PAPER AGENT</span><b>What remains deliberately bounded</b><p>Manual or once-daily opt-in checks, private audit records, stale-feed rejection, position and daily limits, and no live exchange execution.</p></article></section>
    <div className="demo-caveat"><span>i</span><p>Research quality, provider availability, and simulated strategy outcomes depend on the captured inputs. This walkthrough does not claim audited alpha, a provider SLA, institutional certification, or investment advice.</p></div>
    <div className="demo-final-cta"><div><span className="eyebrow small-eyebrow">START THE JOURNEY</span><h2>Bring a question. Keep the evidence.</h2></div><div className="demo-final-actions"><Link className="primary-link" href="/research">Open Research Desk <span>↗</span></Link><Link href="/guide">Read the usage guide <span>→</span></Link></div></div>
  </div>;
}
