import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal/legal.module.css";

export const metadata: Metadata = { title: "Privacy Policy | Tidelight", description: "How Tidelight handles account, research, community, trading connection, and AI support data." };

const sections = [
  ["scope", "Scope"], ["collection", "Data we handle"], ["uses", "How we use data"], ["sharing", "Providers and sharing"], ["visibility", "Your privacy choices"], ["security", "Storage and security"], ["retention", "Retention and deletion"], ["rights", "Your rights"], ["updates", "Updates and contact"],
] as const;

export default function PrivacyPage() {
  return <div className={styles.page}>
    <Link className={styles.back} href="/">← Back to the desk</Link>
    <header className={styles.hero}><span className={styles.eyebrow}>TIDELIGHT / LEGAL</span><h1>Privacy, in plain view.</h1><p>This policy explains what Tidelight handles when you research markets, use the community, connect Bitget, or ask the Tide guide for help.</p><time className={styles.date} dateTime="2026-10-10">Privacy draft · October 10, 2026</time></header>
    <div className={styles.layout}><nav className={styles.toc} aria-label="Privacy sections"><b>ON THIS PAGE</b>{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className={styles.content}>
      <aside className={styles.summary}><h2>The short version</h2><p>Research and account records are tied to your sign-in. Community posts and profiles are public; conversations are limited to participants. Your studio totals appear on your public profile only when you opt in. Connecting Bitget lets the server use encrypted credentials for the trading actions you authorize. Questions sent to AI features can be processed by external model providers.</p></aside>
      <section className={styles.section} id="scope"><h2><span>01</span>Scope</h2><p>This policy covers the Tidelight website and its research, paper trading, live Bitget connection, and research community features. Third-party websites linked from Tidelight have their own privacy terms. Tidelight is a research product; Bitget is a separate exchange.</p></section>
      <section className={styles.section} id="collection"><h2><span>02</span>Data we handle</h2><ul><li><strong>Account and settings:</strong> email, account identifier, authentication factors and events, profile name, handle, avatar, theme choice, research preferences, and session data. Google sign-in can provide account profile details when you use it.</li><li><strong>Research and simulation:</strong> questions, source URLs and passages, generated briefs, watchlists, backtests, paper positions, agent decisions, alerts, and related timestamps.</li><li><strong>Community:</strong> public posts, replies, reactions, follows, profile details, optional shared studio totals, uploaded media, reports and blocks. Direct messages and their metadata are visible to conversation participants and necessary service administrators, not publicly posted.</li><li><strong>Trading connection:</strong> Bitget API key, secret, passphrase, connection mode, order requests and responses, and security events. Credentials are encrypted on the server and are not returned in connection responses.</li><li><strong>Support and technical data:</strong> questions you submit to Tide, the current page context, recent chat context you send, request counts, and server logs needed for operation and abuse prevention. The support request budget records account and time; chat text is not written to its request-budget table.</li></ul></section>
      <section className={styles.section} id="uses"><h2><span>03</span>Why we use it</h2><p>We use account data to sign you in and secure your workspace; research data to deliver briefs, simulations and history; community data to publish posts, deliver messages and enforce safety controls; and trading credentials only for the Bitget connection and orders you choose. We process technical records to operate, troubleshoot and protect the service. We do not represent AI generated material as verified fact or personalized investment advice.</p></section>
      <section className={styles.section} id="sharing"><h2><span>04</span>Providers and sharing</h2><p><strong>Supabase</strong> supports authentication, database records and media storage. <strong>Vercel</strong> hosts the application and processes requests. Research and support prompts may go to <strong>Bitget’s Qwen gateway</strong> or <strong>Google Gemini</strong> when configured; their handling is subject to their own terms. Market data and user-confirmed orders can be sent to <strong>Bitget</strong>. Public source URLs may be fetched from their publishers. An optional AgentKey research data connection, when enabled, may route selected research requests to AgentKey and its data providers. We do not claim these providers never retain prompts or use them for model training; check their policies before entering sensitive material.</p><p>Content you publish to the community is available to other visitors. We do not publish your Bitget credentials, private briefs, direct messages, account email, or trade balances as community content.</p></section>
      <section className={styles.section} id="visibility"><h2><span>05</span>Your privacy choices</h2><p>You can manage your profile and research preferences in <Link href="/settings">Settings</Link>, remove watchlist entries in <Link href="/watchlist">Watchlist</Link>, and disconnect Bitget in <Link href="/trading">Trading</Link>. Public studio usage totals are off until you enable them on your <Link href="/community">community profile</Link>. Turning them off hides the aggregate counts; it does not delete the underlying private activity. Be mindful that others may copy public posts before you remove them. Your browser stores local appearance preferences and essential sign-in state.</p></section>
      <section className={styles.section} id="security"><h2><span>06</span>Storage and security</h2><p>Account-owned tables use access policies to separate users’ private records. Bitget credentials are encrypted before storage; the browser does not receive stored secrets back. Live orders require an explicit confirmation and a recent authenticator check. These controls reduce risk but cannot guarantee absolute security. Use a dedicated Bitget key with only the permissions needed, and revoke it in Bitget if you suspect exposure.</p></section>
      <section className={styles.section} id="retention"><h2><span>07</span>Retention and deletion</h2><p>We keep account-linked records while needed for the feature, security or applicable obligations. Individual watchlist entries, community posts and Bitget connections can be removed through their product controls. Deleting a post does not necessarily remove media that was already copied or cached elsewhere. A scheduled cleanup removes eligible community media no longer referenced by a post after seven days; this describes a cleanup rule, not a guarantee that all uploads disappear seven days after posting. Some authentication, security, backup and provider logs can remain for a limited period under their respective systems and obligations. There is currently no in-app account deletion or full export control; see the request guidance below.</p></section>
      <section className={styles.section} id="rights"><h2><span>08</span>Your rights</h2><p>Depending on where you live, you may ask to access, correct, export, object to or restrict processing of, or delete personal data, and raise a concern with your data protection authority. Nigerian users can consult the <a href="https://ndpc.gov.ng/" target="_blank" rel="noreferrer">Nigeria Data Protection Commission</a>. You can make many corrections in Settings, and remove supported items in the relevant workspace. For a wider privacy request, email <a href="mailto:thedigitalabiola@gmail.com">thedigitalabiola@gmail.com</a>. Do not send identity documents, passwords, API keys, or other private account details through a public issue.</p></section>
      <section className={styles.section} id="updates"><h2><span>09</span>Updates and contact</h2><p>Tidelight is operated by Asiwaju in Nigeria. We may update this policy as features or providers change; the dated version above will be updated, and significant changes will be called out in the product. For privacy or support questions, email <a href="mailto:thedigitalabiola@gmail.com">thedigitalabiola@gmail.com</a> or call <a href="tel:+2349135060079">+234 913 506 0079</a> / <a href="tel:+2348032401443">+234 803 240 1443</a>. This page remains a draft pending final legal review.</p></section>
      <div className={styles.cross}><span>Also read the rules for using the desk.</span><Link href="/terms">Terms of Service ↗</Link></div>
    </div></div>
  </div>;
}
