import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal/legal.module.css";

export const metadata: Metadata = { title: "Terms of Service | Tidelight", description: "Rules and important limits for using Tidelight research, community, simulation, and Bitget trading controls." };

const sections = [
  ["service", "The service"], ["account", "Accounts and security"], ["research", "Research and AI"],
  ["trading", "Trading and simulation"], ["community", "Community conduct"], ["content", "Your content"],
  ["availability", "Availability and changes"], ["responsibility", "Risk and responsibility"], ["contact", "Contact and updates"],
] as const;

export default function TermsPage() {
  return <div className={styles.page}>
    <Link className={styles.back} href="/">← Back to the desk</Link>
    <header className={styles.hero}><span className={styles.eyebrow}>TIDELIGHT / LEGAL</span><h1>A clearer way to use the desk.</h1><p>These terms describe what Tidelight offers, how its research community works, and the controls around simulations and Bitget orders.</p><time className={styles.date} dateTime="2026-10-10">Product terms draft · October 10, 2026</time></header>
    <div className={styles.layout}><nav className={styles.toc} aria-label="Terms sections"><b>ON THIS PAGE</b>{sections.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><div className={styles.content}>
      <aside className={styles.summary}><h2>Before you begin</h2><p>Tidelight organizes research and gives you controls for paper scenarios and user-confirmed Bitget spot orders. Its AI can be wrong, sources can be stale, and a simulated result does not predict a live outcome. You decide whether to trade and confirm each live order yourself.</p></aside>
      <section className={styles.section} id="service"><h2><span>01</span>The service</h2><p>Tidelight provides market research tools, evidence briefs, asset views, strategy experiments, an agent flow, paper trading features, community posts and messages, and an optional connection to Bitget for eligible spot instruments. Features may vary by region, provider availability, account status, or configuration. Tidelight is separate from Bitget and other linked providers.</p></section>
      <section className={styles.section} id="account"><h2><span>02</span>Accounts and security</h2><p>Keep your account and authenticator secure and provide accurate information. You are responsible for activity you authorize with your account. Do not put passwords, one-time codes, API keys, passphrases, or private financial information in posts, messages, or Tide chat. Use the dedicated encrypted connection form for a Bitget API credential, grant only the permissions needed, leave withdrawals disabled, and revoke the key in Bitget if compromised. We may restrict access to protect users or the service from abuse.</p></section>
      <section className={styles.section} id="research"><h2><span>03</span>Research and AI</h2><p>Research briefs and assistant responses are informational and may contain incomplete, incorrect, outdated, or contradictory material. A source match confirms a passage was captured; it does not independently establish its truth. Check the underlying publisher, timestamps, market conditions, and any opposing evidence. Tide can explain the product and suggest steps, but cannot inspect your private account through chat, change settings, approve an order, or act as a financial adviser.</p></section>
      <section className={styles.section} id="trading"><h2><span>04</span>Trading and simulation</h2><p>Paper balances, backtests, Nightwatch fills, and demo funds are simulations, not cash or guaranteed executable prices. Live Bitget orders can result in a real financial loss and require your explicit confirmation and an authenticator check. Price, liquidity, fees, slippage, market hours, token issuer terms, and exchange conditions may differ from a displayed estimate. Tidelight restricts supported instruments and order size, but these controls do not eliminate trading risk. You must follow Bitget’s applicable terms and your local laws. We do not promise profit, availability, or suitability of a strategy.</p></section>
      <section className={styles.section} id="community"><h2><span>05</span>Community conduct</h2><p>Post only material you are allowed to share. Do not impersonate others, harass, spam, publish secrets or private information, mislead others with fabricated evidence, or use the community to manipulate markets. Public posts, replies, profiles, and any Studio totals you choose to share can be seen and copied by others. Direct messages are intended for participants. We may remove content or limit accounts to address abuse or legal requests.</p></section>
      <section className={styles.section} id="content"><h2><span>06</span>Your content</h2><p>You retain rights you have in your posts and research materials. By submitting content, you allow Tidelight to store, process, display, and deliver it as needed for the feature you chose, including showing public posts to other users. Do not submit material that violates another person’s rights. External source content remains subject to the publisher’s rights and terms. See the <Link href="/privacy">Privacy Policy</Link> for handling and visibility details.</p></section>
      <section className={styles.section} id="availability"><h2><span>07</span>Availability and changes</h2><p>Features and external data sources can be interrupted, delayed, changed, or removed. We may improve the service and update these terms; material changes should be called out in the product with a revised effective date. Avoid relying on Tidelight as your sole record of an order or the sole source for a time-sensitive financial decision. Check Bitget directly for the status of an exchange order.</p></section>
      <section className={styles.section} id="responsibility"><h2><span>08</span>Risk and responsibility</h2><p>Use your own judgment and seek qualified professional advice where needed. Nothing in the service is a promise of a particular result or a substitute for your own due diligence. These draft terms are governed by the laws of the Federal Republic of Nigeria, while preserving any mandatory rights that apply where you live. A qualified review is still needed before these terms are treated as a final agreement.</p></section>
      <section className={styles.section} id="contact"><h2><span>09</span>Contact and updates</h2><p>Tidelight is operated by Asiwaju. For product support or privacy questions, email <a href="mailto:thedigitalabiola@gmail.com">thedigitalabiola@gmail.com</a> or contact <a href="tel:+2349135060079">+234 913 506 0079</a> / <a href="tel:+2348032401443">+234 803 240 1443</a>. These terms remain a product draft while final operator identity and legal review are completed. Do not send API keys, passwords, or private account details by email, phone, or a public repository issue.</p></section>
      <div className={styles.cross}><span>How your data moves through Tidelight.</span><Link href="/privacy">Privacy Policy ↗</Link></div>
    </div></div>
  </div>;
}
