"use client";
import Link from "next/link";
import Image from "next/image";
import {useRouter} from "next/navigation";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import "../community/community.css";
type Profile={id:string;handle:string;display_name:string;avatar_url:string|null};
type MediaItem={url:string;kind:"image"|"video"|"audio"|"pdf";name:string;mime:string;size:number};
type Post={id:string;body:string;symbol:string|null;stance:string;source_url:string|null;media:MediaItem[];mediaExpired?:boolean;reply_to:string|null;quote_post_id:string|null;created_at:string;author:Profile;quoted?:{body:string;symbol:string|null;author:{handle:string;display_name:string}}|null;likes:number;reposts:number;replies:number;liked:boolean;reposted:boolean;saved:boolean;reason?:string;feedScore?:number};
function downloadUrl(item:MediaItem){const url=new URL(item.url);url.searchParams.set("download",item.name);return url.toString()}
async function stampImage(file:File):Promise<File>{
 if(!["image/jpeg","image/png","image/webp"].includes(file.type))return file;
 try{
  const bitmap=await createImageBitmap(file),scale=Math.min(1,2400/bitmap.width,2400/bitmap.height),canvas=document.createElement("canvas");
  canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);
  const ctx=canvas.getContext("2d");if(!ctx)return file;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
  const pad=Math.max(9,canvas.width*.017),height=Math.max(42,canvas.width*.075),width=Math.min(canvas.width-pad*2,Math.max(160,canvas.width*.4)),x=pad,y=Math.max(0,canvas.height-height-pad);
  ctx.fillStyle="rgba(4,18,17,.82)";ctx.fillRect(x,y,width,height);ctx.strokeStyle="rgba(146,232,195,.7)";ctx.strokeRect(x,y,width,height);
  try{const response=await fetch("/tidelight-icon-192.png",{cache:"force-cache"});if(response.ok){const logo=await createImageBitmap(await response.blob()),size=height*.68;ctx.drawImage(logo,x+height*.12,y+(height-size)/2,size,size);logo.close()}}catch{}
  ctx.fillStyle="#9be8c4";ctx.font="600 "+Math.max(11,height*.25)+"px Arial,sans-serif";ctx.fillText("TIDELIGHT",x+height*.92,y+height*.45);
  ctx.fillStyle="#e5f6ed";ctx.font="500 "+Math.max(8,height*.14)+"px Arial,sans-serif";ctx.fillText("RESEARCH DESK",x+height*.92,y+height*.7);
  const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,file.type,.92));if(!blob)return file;
  return new File([blob],file.name,{type:file.type,lastModified:file.lastModified});
 }catch{return file}
}
export default function CommunityDesk({signedIn,userId,profile}:{signedIn:boolean;userId:string|null;profile:Profile|null}){
 const [posts,setPosts]=useState<Post[]>([]),[tab,setTab]=useState<"for-you"|"latest">("for-you"),[body,setBody]=useState(""),[symbol,setSymbol]=useState(""),[stance,setStance]=useState("watching"),[source,setSource]=useState("");
 const [quote,setQuote]=useState<Post|null>(null),[replyTo,setReplyTo]=useState<Post|null>(null),[thread,setThread]=useState<Post[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");
 const router=useRouter();
 const [profileSearch,setProfileSearch]=useState("");
 const [feedSearch,setFeedSearch]=useState("");
 const [files,setFiles]=useState<File[]>([]),[recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null);
 const refresh=useCallback(async()=>{const r=await fetch("/api/community/feed",{cache:"no-store"});const d=await r.json();if(r.ok)setPosts(d.posts??[]);else setError(d.error??"Feed unavailable.");},[]);
 useEffect(()=>{let active=true;const controller=new AbortController();fetch("/api/community/feed",{cache:"no-store",signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error??"Feed unavailable.");if(active)setPosts(data.posts??[])}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Feed unavailable.")});return()=>{active=false;controller.abort()}},[]);
 useEffect(()=>{const hash=window.location.hash;if(!hash.startsWith("#post-"))return;const target=document.getElementById(hash.slice(1));target?.scrollIntoView({block:"center"})},[posts]);
 useEffect(()=>()=>{if(recorder.current?.state=== "recording")recorder.current.stop();recorder.current?.stream.getTracks().forEach(track=>track.stop())},[]);
 const sorted=useMemo(()=>{const query=feedSearch.trim().toLocaleLowerCase();const items=posts.filter(post=>!query||[post.body,post.symbol,post.author?.display_name,post.author?.handle].some(value=>value?.toLocaleLowerCase().includes(query)));if(tab==="latest")return items.sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));return items.sort((a,b)=>{const score=(x:Post)=>{const age=(Date.now()-Date.parse(x.created_at))/3600000;return x.feedScore??((x.reason?8:0)+Math.log1p(x.likes+x.reposts*1.5+x.replies)*2-Math.min(age,96)/18)};return score(b)-score(a)});},[posts,tab,feedSearch]);
 async function publish(e:React.FormEvent,reply?:Post){e.preventDefault();if(!signedIn){router.push("/login");return}setBusy(true);setError("");try{if(files.length>4)throw new Error("Attach up to four files to a post or reply.");if(files.reduce((total,file)=>total+file.size,0)>60*1024*1024)throw new Error("Attachments must total 60 MB or less.");const supabase=createClient();const media:MediaItem[]=[];for(const original of files){const file=await stampImage(original);const allowed=["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/webm","application/pdf","audio/mpeg","audio/mp4","audio/wav","audio/ogg","audio/webm","audio/x-m4a"];if(!allowed.includes(file.type))throw new Error("Choose an image, MP4/WebM video, PDF, or audio recording.");const max=file.type.startsWith("video/")?25*1024*1024:file.type==="application/pdf"?15*1024*1024:15*1024*1024;if(file.size>max)throw new Error(file.type.startsWith("video/")?"Videos must be 25 MB or smaller.":"Each attachment must be 15 MB or smaller.");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-90)||"attachment";const path=userId+"/"+crypto.randomUUID()+"-"+safeName;const {error:uploadError}=await supabase.storage.from("community-media").upload(path,file,{contentType:file.type,cacheControl:"604800",upsert:false});if(uploadError)throw new Error("A file could not be uploaded: "+uploadError.message);const url=supabase.storage.from("community-media").getPublicUrl(path).data.publicUrl;const kind=file.type.startsWith("image/")?"image":file.type.startsWith("video/")?"video":file.type==="application/pdf"?"pdf":"audio";media.push({url,kind,name:file.name,mime:file.type,size:file.size})}const r=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body,symbol,stance,sourceUrl:source,replyTo:reply?.id,quotePostId:quote?.id,media})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not publish.");setBody("");setSource("");setSymbol("");setFiles([]);setQuote(null);setReplyTo(null);setToast(reply?"Reply added to the research thread.":quote?"Research quote published.":"Your Tidelight note is live.");setTimeout(()=>setToast(""),2600);await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not publish.")}finally{setBusy(false)}}
 async function react(post:Post,action:"like"|"repost"){if(!signedIn){router.push("/login");return}const key=action==="like"?"liked":"reposted",count=action==="like"?"likes":"reposts",was=post[key];const patch=(items:Post[])=>items.map(p=>p.id===post.id?{...p,[key]:!was,[count]:p[count]+(was?-1:1)}:p);setPosts(patch);setThread(patch);try{const r=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,postId:post.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setToast(action==="like"?(d.active?"Saved to your signal.":"Like removed."):(d.active?"Reposted to your desk.":"Repost removed."));setTimeout(()=>setToast(""),2100)}catch(e){const rollback=(items:Post[])=>items.map(p=>p.id===post.id?{...p,[key]:was,[count]:p[count]+(was?1:-1)}:p);setPosts(rollback);setThread(rollback);setError(e instanceof Error?e.message:"Could not save that action.")}}
 async function toggleBookmark(post:Post){if(!signedIn){router.push("/login");return}const was=post.saved;const patch=(items:Post[])=>items.map(item=>item.id===post.id?{...item,saved:!was}:item);setPosts(patch);setThread(patch);try{const response=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"bookmark",postId:post.id})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save post.");setToast(result.active?"Saved to your private research list.":"Removed from saved posts.");setTimeout(()=>setToast(""),2200)}catch(cause){const rollback=(items:Post[])=>items.map(item=>item.id===post.id?{...item,saved:was}:item);setPosts(rollback);setThread(rollback);setError(cause instanceof Error?cause.message:"Could not update saved posts.")}}
 async function share(post:Post){const url=new URL("/community#post-"+encodeURIComponent(post.id),window.location.origin).toString();try{if(navigator.share){await navigator.share({title:"Tidelight research note",url});return}await navigator.clipboard.writeText(url);setToast("Link copied to clipboard.")}catch(cause){if(cause instanceof Error&&cause.name==="AbortError")return;setError("Could not share this note. Copy its URL from the address bar instead.")}}
 async function moderate(post:Post,action:"report"|"block"){if(!signedIn){router.push("/login");return}try{const r=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,postId:post.id,reason:"misinformation"})});const result=await r.json();if(!r.ok)throw new Error(result.error??"Could not update community safety settings.");if(action==="block")setPosts(items=>items.filter(item=>item.author.id!==post.author.id));setToast(action==="block"?"Member muted from your desk.":"Report sent to Tidelight moderators.");setTimeout(()=>setToast(""),2500)}catch(cause){setError(cause instanceof Error?cause.message:"Could not update community safety settings.")}}
 async function openThread(post:Post){try{const response=await fetch("/api/community/feed?thread="+post.id);const data=await response.json();if(!response.ok)throw new Error(data.error??"Thread unavailable.");setReplyTo(post);setQuote(null);setThread(data.posts??[]);document.querySelector(".community-composer")?.scrollIntoView({behavior:"smooth",block:"center"})}catch(cause){setError(cause instanceof Error?cause.message:"Thread unavailable.")}}
 return <main className="content-wrap inner-page community-page">
  <header className="page-heading community-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> TIDELIGHT / RESEARCH COMMUNITY</div><h1>The research community<span>.</span></h1><p>Follow the evidence. Share a view. Find your people.</p></div><div className="community-live"><i/>US EQUITIES + REALITY RTOKENS</div></header>
  {toast?<div className="community-toast" role="status">✳ {toast}</div>:null}{error?<div className="community-error" role="alert">{error}</div>:null}
  {!signedIn?<section className="community-gate"><h2>Join the research desk</h2><p>Sign in to publish notes, reply, like, repost, quote, and message other members.</p><Link href="/login" className="community-primary">Sign in to Tidelight ↗</Link></section>:!profile?<section className="community-gate"><h2>Set up your research identity</h2><p>Add a display name, handle, and optional profile photo in Settings before publishing.</p><Link href="/settings" className="community-primary">Complete profile ↗</Link></section>:null}
  <div className="community-layout"><nav className="community-rail" aria-label="Community navigation"><Link href="/community" className="active"><span>⌂</span> Research feed</Link><Link href="/community/messages"><span>✉</span> Messages</Link>{profile?<><Link href={"/community/"+encodeURIComponent(profile.handle)}><span>◉</span> My profile</Link><Link href={"/community/"+encodeURIComponent(profile.handle)+"?tab=saved"}><span>▣</span> Saved research</Link></>:null}<Link href="/watchlist"><span>☆</span> Watchlist</Link><Link href="/flow"><span>↗</span> Research studio</Link><div className="community-rail-note"><span className="eyebrow small-eyebrow">A CLEARER SIGNAL</span><p>Ideas are stronger when their evidence travels with them.</p></div></nav><section className="community-main">
   {profile?<form className="community-composer" onSubmit={e=>void publish(e,replyTo??undefined)}><div className="community-composer-top"><div className="community-avatar">{profile.avatar_url?<Image unoptimized width={94} height={94} src={profile.avatar_url} alt=""/>:profile.display_name.slice(0,1)}</div><div><b>{profile.display_name}</b><small>@{profile.handle} · {replyTo ? "replying to @"+replyTo.author.handle : quote ? "quoting a desk note" : "new research note"}</small></div></div>
    {quote?<div className="community-quote-preview"><b>@{quote.author.handle} · {quote.symbol??"Research note"}</b><p>{quote.body}</p><button type="button" onClick={()=>setQuote(null)}>Remove quote</button></div>:null}
    <textarea aria-label="Research note" value={body} maxLength={1800} onChange={e=>setBody(e.target.value)} placeholder={replyTo?"Add evidence, a question, or a different read…":"What changed for a US issuer or its Reality token?"} required/>
    <details className="community-composer-details"><summary>Add research context</summary><div className="community-composer-fields"><label>ISSUER / RTOKEN<input value={symbol} maxLength={32} onChange={e=>setSymbol(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="NVDA or RNVDAUSDT"/></label><label>YOUR READ<select value={stance} onChange={e=>setStance(e.target.value)}><option value="watching">Watching</option><option value="bullish">Positive case</option><option value="bearish">Risk case</option><option value="question">Question</option><option value="neutral">Mixed / neutral</option></select></label></div>
    {!replyTo?<label className="community-source">SOURCE LINK <input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https:// SEC filing, issuer release, or article"/></label>:null}</details>
    <div className="community-upload-row"><label className="community-upload-button">＋ Add media<input type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm,application/pdf,audio/mpeg,audio/mp4,audio/wav,audio/ogg,audio/webm,audio/x-m4a" onChange={e=>{const chosen=Array.from(e.target.files??[]);setFiles(old=>[...old,...chosen].slice(0,4));e.currentTarget.value=""}}/></label><button type="button" className={"community-upload-button"+(recording?" recording":"")} onClick={async()=>{try{if(recording){recorder.current?.stop();return}if(files.length>=4)throw new Error("You can attach up to four files.");const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};rec.onstop=()=>{const mime=(rec.mimeType||"audio/webm").split(";")[0];const blob=new Blob(chunks,{type:mime});const extension=mime==="audio/ogg"?"ogg":"webm";const file=new File([blob],"tidelight-voice-note."+extension,{type:mime});setFiles(old=>[...old,file].slice(0,4));stream.getTracks().forEach(track=>track.stop());setRecording(false)};rec.start();setRecording(true)}catch(e){setRecording(false);setError(e instanceof Error?e.message:"Allow microphone access to record a voice note.")}}}>{recording?"■ Stop recording":"◉ Record voice note"}</button><span>Up to 4 files · images, video, PDF, audio</span></div><small className="community-watermark-note">Images receive a Tidelight research watermark. Media downloads stay available for 7 days.</small>
    {files.length?<div className="community-file-list">{files.map((file,index)=><div key={index}><span>{file.type.startsWith("audio/")?"◉":file.type==="application/pdf"?"PDF":file.type.startsWith("video/")?"▷":"▧"} {file.name} · {(file.size/1048576).toFixed(1)} MB</span><button type="button" onClick={()=>setFiles(old=>old.filter((_,i)=>i!==index))} aria-label={"Remove "+file.name}>×</button></div>)}</div>:null}
    <div className="community-composer-foot"><span>{body.length}/1,800 · Keep claims traceable to sources.</span><button className="community-primary" disabled={busy||!body.trim()}>{busy?"Uploading & publishing…":replyTo?"Reply to thread":"Post research note"}</button></div>
   </form>:null}
   <div className="community-feed-head"><div><span className="eyebrow small-eyebrow">THE DESK FEED</span><h2>Research in conversation</h2></div><div className="community-tabs" aria-label="Feed order"><button className={tab==="for-you"?"active":""} onClick={()=>setTab("for-you")}>For your desk</button><button className={tab==="latest"?"active":""} onClick={()=>setTab("latest")}>Latest</button></div></div>
   <label className="community-feed-search"><span>Search public research</span><input type="search" value={feedSearch} onChange={event=>setFeedSearch(event.target.value)} placeholder="Issuer, member, or topic" aria-label="Search loaded research notes"/><small>Searches notes currently loaded on this page.</small></label>
   {tab==="for-you"&&profile?<p className="community-personal-note">Ranked using your watchlist, recent research, Strategy Lab runs, and reactions.</p>:null}
   {sorted.length?sorted.map(post=><article className="community-post" id={"post-"+post.id} key={post.id}><div className="community-post-head"><div className="community-avatar">{post.author?.avatar_url?<Image unoptimized width={94} height={94} src={post.author.avatar_url} alt=""/>:(post.author?.display_name??"T").slice(0,1)}</div><div className="community-author"><Link href={"/community/"+encodeURIComponent(post.author?.handle??"")}><b>{post.author?.display_name??"Tidelight member"}</b></Link><small><Link href={"/community/"+encodeURIComponent(post.author?.handle??"")}>@{post.author?.handle}</Link> · {new Date(post.created_at).toLocaleString()}</small></div>{post.symbol?<span className="community-symbol">{post.symbol}</span>:null}</div>
    {post.reason&&tab==="for-you"?<div className="community-reason">✳ {post.reason}</div>:null}<div className="community-post-copy"><span className={"community-stance "+post.stance}>{post.stance==="bullish"?"POSITIVE CASE":post.stance==="bearish"?"RISK CASE":post.stance.toUpperCase()}</span><p>{post.body}</p>{post.source_url?<a className="community-evidence" href={post.source_url} target="_blank" rel="noreferrer">Evidence link ↗</a>:null}</div>
    {post.media?.length?<div className="community-media-grid">{post.media.map((item,index)=><div className={"community-media-item "+item.kind} key={item.url+index}>{item.kind==="image"?<a href={item.url} target="_blank" rel="noreferrer"><Image unoptimized width={1200} height={800} src={item.url} alt={item.name}/></a>:item.kind==="video"?<video controls preload="metadata" src={item.url}/>:item.kind==="audio"?<div><b>◉ Voice / audio note</b><audio controls preload="metadata" src={item.url}/></div>:<a className="community-pdf" href={item.url} target="_blank" rel="noreferrer"><span>PDF</span><b>{item.name}</b><small>Open document ↗</small></a>}<a className="community-download" href={downloadUrl(item)} download={item.name}>↓ Download from Tidelight</a></div>)}</div>:null}{post.mediaExpired?<p className="community-media-expired">Attachments were removed after 7 days.</p>:null}
    {post.quoted?<div className="community-quote-preview"><b>@{post.quoted.author?.handle} · {post.quoted.symbol??"Research note"}</b><p>{post.quoted.body}</p></div>:null}
    <div className="community-actions"><button className={post.liked?"is-liked":""} onClick={()=>void react(post,"like")} aria-pressed={post.liked}><span>♥</span> Like <small>{post.likes}</small></button><button className={post.saved?"is-saved":""} onClick={()=>void toggleBookmark(post)} aria-pressed={post.saved}><span>▣</span> {post.saved?"Saved":"Save"}</button><button className={post.reposted?"is-reposted":""} onClick={()=>void react(post,"repost")} aria-pressed={post.reposted}><span>↻</span> Repost <small>{post.reposts}</small></button><button onClick={()=>{setQuote(post);setReplyTo(null);window.scrollTo({top:0,behavior:"smooth"})}}><span>❞</span> Quote</button><button onClick={()=>void openThread(post)}><span>↳</span> Reply <small>{post.replies}</small></button><button onClick={()=>{router.push("/community/messages?handle="+encodeURIComponent(post.author.handle))}}>Message</button><button onClick={()=>void share(post)} aria-label={"Share post by "+(post.author?.display_name??"Tidelight member")}><span>↗</span> Share</button><details className="community-more-actions"><summary aria-label="More actions">•••</summary><div><button onClick={()=>void moderate(post,"report")}>Report</button><button onClick={()=>void moderate(post,"block")}>Mute member</button></div></details></div>
   </article>):<div className="community-empty"><span>✳</span><b>{feedSearch?"No matching research notes.":"The desk is quiet for now."}</b><p>{feedSearch?"Try a different ticker, member, or phrase. The search covers the notes loaded on this page.":"Start with a source-backed note on a listed US issuer or a Reality rToken. Your activity will shape the feed over time."}</p></div>}
   {replyTo?<section className="community-thread"><div className="community-thread-head"><div><span className="eyebrow small-eyebrow">RESEARCH THREAD</span><h3>Keep the discussion attached to its evidence.</h3></div><button onClick={()=>{setReplyTo(null);setThread([])}}>Close</button></div>{thread.map(item=><article className="community-reply" key={item.id}><b><Link href={"/community/"+encodeURIComponent(item.author.handle)}>{item.author.display_name} <small>@{item.author.handle}</small></Link></b><p>{item.body}</p>{item.source_url?<a href={item.source_url} target="_blank" rel="noreferrer">Source ↗</a>:null}{item.media?.length?<div className="community-media-grid">{item.media.map((media,index)=><div className={"community-media-item "+media.kind} key={media.url+index}>{media.kind==="image"?<a href={media.url} target="_blank" rel="noreferrer"><Image unoptimized width={1200} height={800} src={media.url} alt={media.name}/></a>:media.kind==="video"?<video controls preload="metadata" src={media.url}/>:media.kind==="audio"?<audio controls preload="metadata" src={media.url}/>:<a className="community-pdf" href={media.url} target="_blank" rel="noreferrer"><span>PDF</span><b>{media.name}</b><small>Open document ↗</small></a>}<a className="community-download" href={downloadUrl(media)} download={media.name}>↓ Download from Tidelight</a></div>)}</div>:null}{item.mediaExpired?<p className="community-media-expired">Attachments were removed after 7 days.</p>:null}<button className={"community-comment-like"+(item.liked?" is-liked":"")} onClick={()=>void react(item,"like")} aria-pressed={item.liked}>♥ Like · {item.likes}</button></article>)}</section>:null}
  </section>
  <aside className="community-aside"><section className="community-profile-tools"><span className="eyebrow small-eyebrow">TIDELIGHT PEOPLE</span><h3>Find a research voice.</h3><form className="community-profile-search" onSubmit={event=>{event.preventDefault();const target=profileSearch.trim().replace(/^@/,"");if(target)router.push("/community/"+encodeURIComponent(target))}}><input value={profileSearch} onChange={event=>setProfileSearch(event.target.value)} placeholder="@username" aria-label="Search community username" required/><button className="community-primary">View profile ↗</button></form>{profile?<Link href={"/community/"+encodeURIComponent(profile.handle)}>Open your profile ↗</Link>:null}</section><section><span className="eyebrow small-eyebrow">YOUR SIGNAL GRAPH</span><h3>Built around what you follow.</h3><p>Notes linked to issuer events, SEC filings, and Reality pairs surface closer to the top as you research and react.</p><div className="community-signal-list"><span>01 <b>Watchlist focus</b></span><span>02 <b>Research trail</b></span><span>03 <b>Helpful reactions</b></span><span>04 <b>Fresh evidence</b></span></div><Link href="/watchlist">Tune your watchlist ↗</Link></section>
  <section className="community-inbox"><span className="eyebrow small-eyebrow">PRIVATE DESK NOTES</span><h3>Take the conversation further.</h3><p>Compare a source or a scenario in a private conversation with another researcher.</p><Link href="/community/messages" className="community-primary">Open messages ↗</Link></section>
  <section className="community-safety"><span className="eyebrow small-eyebrow">COMMUNITY STANDARD</span><p>Separate issuer facts from token-market claims. Be clear about uncertainty. No trade calls, promotion spam, or unsupported claims.</p><small>Messages are limited to conversation participants; public notes stay readable to guests.</small></section>
  </aside></div>
 </main>
}