"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import "../community/community.css";
type Profile={id:string;handle:string;display_name:string;avatar_url:string|null};
type MediaItem={url:string;kind:"image"|"video"|"audio"|"pdf";name:string;mime:string;size:number};
type Post={id:string;body:string;symbol:string|null;stance:string;source_url:string|null;media:MediaItem[];mediaExpired?:boolean;reply_to:string|null;quote_post_id:string|null;created_at:string;author:Profile;quoted?:{body:string;symbol:string|null;author:{handle:string;display_name:string}}|null;likes:number;reposts:number;replies:number;liked:boolean;reposted:boolean;saved:boolean;reason?:string;feedScore?:number};
type Message={id:string;sender_id:string;body:string;created_at:string};
export default function CommunityDesk({signedIn,userId,profile}:{signedIn:boolean;userId:string|null;profile:Profile|null}){
 const [posts,setPosts]=useState<Post[]>([]),[tab,setTab]=useState<"for-you"|"latest">("for-you"),[body,setBody]=useState(""),[symbol,setSymbol]=useState(""),[stance,setStance]=useState("watching"),[source,setSource]=useState("");
 const [quote,setQuote]=useState<Post|null>(null),[replyTo,setReplyTo]=useState<Post|null>(null),[thread,setThread]=useState<Post[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");
 const [handle,setHandle]=useState(""),[message,setMessage]=useState(""),[messages,setMessages]=useState<Message[]>([]),[peerName,setPeerName]=useState(""),[profileSearch,setProfileSearch]=useState("");
 const [files,setFiles]=useState<File[]>([]),[recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null);
 const refresh=useCallback(async()=>{const r=await fetch("/api/community/feed",{cache:"no-store"});const d=await r.json();if(r.ok)setPosts(d.posts??[]);else setError(d.error??"Feed unavailable.");},[]);
 useEffect(()=>{void refresh()},[refresh]);
 const sorted=useMemo(()=>{const items=[...posts];if(tab==="latest")return items.sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));return items.sort((a,b)=>{const score=(x:Post)=>{const age=(Date.now()-Date.parse(x.created_at))/3600000;return x.feedScore??((x.reason?8:0)+Math.log1p(x.likes+x.reposts*1.5+x.replies)*2-Math.min(age,96)/18)};return score(b)-score(a)});},[posts,tab]);
 async function publish(e:React.FormEvent,reply?:Post){e.preventDefault();if(!signedIn){location.href="/login";return}setBusy(true);setError("");try{if(files.length>4)throw new Error("Attach up to four files to a post or reply.");if(files.reduce((total,file)=>total+file.size,0)>60*1024*1024)throw new Error("Attachments must total 60 MB or less.");const supabase=createClient();const media:MediaItem[]=[];for(const file of files){const allowed=["image/jpeg","image/png","image/webp","image/gif","video/mp4","video/webm","application/pdf","audio/mpeg","audio/mp4","audio/wav","audio/ogg","audio/webm","audio/x-m4a"];if(!allowed.includes(file.type))throw new Error("Choose an image, MP4/WebM video, PDF, or audio recording.");const max=file.type.startsWith("video/")?25*1024*1024:file.type==="application/pdf"?15*1024*1024:15*1024*1024;if(file.size>max)throw new Error(file.type.startsWith("video/")?"Videos must be 25 MB or smaller.":"Each attachment must be 15 MB or smaller.");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-90)||"attachment";const path=userId+"/"+crypto.randomUUID()+"-"+safeName;const {error:uploadError}=await supabase.storage.from("community-media").upload(path,file,{contentType:file.type,cacheControl:"3600",upsert:false});if(uploadError)throw new Error("A file could not be uploaded: "+uploadError.message);const url=supabase.storage.from("community-media").getPublicUrl(path).data.publicUrl;const kind=file.type.startsWith("image/")?"image":file.type.startsWith("video/")?"video":file.type==="application/pdf"?"pdf":"audio";media.push({url,kind,name:file.name,mime:file.type,size:file.size})}const r=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body,symbol,stance,sourceUrl:source,replyTo:reply?.id,quotePostId:quote?.id,media})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Could not publish.");setBody("");setSource("");setSymbol("");setFiles([]);setQuote(null);setReplyTo(null);setToast(reply?"Reply added to the research thread.":quote?"Research quote published.":"Your Tidelight note is live.");setTimeout(()=>setToast(""),2600);await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not publish.")}finally{setBusy(false)}}
 async function react(post:Post,action:"like"|"repost"){if(!signedIn){location.href="/login";return}const key=action==="like"?"liked":"reposted",count=action==="like"?"likes":"reposts",was=post[key];const patch=(items:Post[])=>items.map(p=>p.id===post.id?{...p,[key]:!was,[count]:p[count]+(was?-1:1)}:p);setPosts(patch);setThread(patch);try{const r=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,postId:post.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setToast(action==="like"?(d.active?"Saved to your signal.":"Like removed."):(d.active?"Reposted to your desk.":"Repost removed."));setTimeout(()=>setToast(""),2100)}catch(e){const rollback=(items:Post[])=>items.map(p=>p.id===post.id?{...p,[key]:was,[count]:p[count]+(was?1:-1)}:p);setPosts(rollback);setThread(rollback);setError(e instanceof Error?e.message:"Could not save that action.")}}
 async function toggleBookmark(post:Post){if(!signedIn){location.href="/login";return}const was=post.saved;const patch=(items:Post[])=>items.map(item=>item.id===post.id?{...item,saved:!was}:item);setPosts(patch);setThread(patch);try{const response=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"bookmark",postId:post.id})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save post.");setToast(result.active?"Saved to your private research list.":"Removed from saved posts.");setTimeout(()=>setToast(""),2200)}catch(cause){const rollback=(items:Post[])=>items.map(item=>item.id===post.id?{...item,saved:was}:item);setPosts(rollback);setThread(rollback);setError(cause instanceof Error?cause.message:"Could not update saved posts.")}}
 async function moderate(post:Post,action:"report"|"block"){if(!signedIn){location.href="/login";return}const r=await fetch("/api/community/feed",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,postId:post.id,reason:"misinformation"})});const result=await r.json();if(!r.ok){setError(result.error??"Could not update community safety settings.");return}if(action==="block")setPosts(items=>items.filter(item=>item.author.id!==post.author.id));setToast(action==="block"?"Member muted from your desk.":"Report sent to Tidelight moderators.");setTimeout(()=>setToast(""),2500)}
 async function openThread(post:Post){setReplyTo(post);const r=await fetch("/api/community/feed?thread="+post.id);const d=await r.json();setThread(d.posts??[])}
 async function openMessages(){if(!handle.trim())return;setError("");const r=await fetch("/api/community/messages?handle="+encodeURIComponent(handle));const d=await r.json();if(!r.ok){setError(d.error);return}setPeerName(d.peer.display_name+" · @"+d.peer.handle);setMessages(d.messages??[])}
 async function sendMessage(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/community/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({handle,body:message})});const d=await r.json();if(!r.ok){setError(d.error);return}setMessages(m=>[...m,d.message]);setMessage("");setPeerName(d.peer.display_name+" · @"+d.peer.handle)}
 return <main className="content-wrap inner-page community-page">
  <header className="page-heading community-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> TIDELIGHT / RESEARCH COMMUNITY</div><h1>Compare notes.<br/><span>Follow the evidence.</span></h1><p>A focused room for tokenized US equities: issuer events, Reality-token context, and the evidence behind each view.</p></div><div className="community-live"><i/>US EQUITIES + REALITY RTOKENS</div></header>
  {toast?<div className="community-toast" role="status">✳ {toast}</div>:null}{error?<div className="community-error" role="alert">{error}</div>:null}
  {!signedIn?<section className="community-gate"><h2>Join the research desk</h2><p>Sign in to publish notes, reply, like, repost, quote, and message other members.</p><Link href="/login" className="community-primary">Sign in to Tidelight ↗</Link></section>:!profile?<section className="community-gate"><h2>Set up your research identity</h2><p>Add a display name, handle, and optional profile photo in Settings before publishing.</p><Link href="/settings" className="community-primary">Complete profile ↗</Link></section>:null}
  <div className="community-layout"><section className="community-main">
   {profile?<form className="community-composer" onSubmit={e=>void publish(e,replyTo??undefined)}><div className="community-composer-top"><div className="community-avatar">{profile.avatar_url?<img src={profile.avatar_url} alt=""/>:profile.display_name.slice(0,1)}</div><div><b>{profile.display_name}</b><small>@{profile.handle} · {replyTo ? "replying to @"+replyTo.author.handle : quote ? "quoting a desk note" : "new research note"}</small></div></div>
    {quote?<div className="community-quote-preview"><b>@{quote.author.handle} · {quote.symbol??"Research note"}</b><p>{quote.body}</p><button type="button" onClick={()=>setQuote(null)}>Remove quote</button></div>:null}
    <textarea value={body} maxLength={1800} onChange={e=>setBody(e.target.value)} placeholder={replyTo?"Add evidence, a question, or a different read…":"What changed for a US issuer or its Reality token?"} required/>
    <div className="community-composer-fields"><label>ISSUER / RTOKEN<input value={symbol} maxLength={32} onChange={e=>setSymbol(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="NVDA or RNVDAUSDT"/></label><label>YOUR READ<select value={stance} onChange={e=>setStance(e.target.value)}><option value="watching">Watching</option><option value="bullish">Positive case</option><option value="bearish">Risk case</option><option value="question">Question</option><option value="neutral">Mixed / neutral</option></select></label></div>
    {!replyTo?<label className="community-source">SOURCE LINK <input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https:// SEC filing, issuer release, or article"/></label>:null}
    <div className="community-upload-row"><label className="community-upload-button">＋ Add media<input type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm,application/pdf,audio/mpeg,audio/mp4,audio/wav,audio/ogg,audio/webm,audio/x-m4a" onChange={e=>{const chosen=Array.from(e.target.files??[]);setFiles(old=>[...old,...chosen].slice(0,4));e.currentTarget.value=""}}/></label><button type="button" className={"community-upload-button"+(recording?" recording":"")} onClick={async()=>{try{if(recording){recorder.current?.stop();return}if(files.length>=4)throw new Error("You can attach up to four files.");const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};rec.onstop=()=>{const mime=(rec.mimeType||"audio/webm").split(";")[0];const blob=new Blob(chunks,{type:mime});const extension=mime==="audio/ogg"?"ogg":"webm";const file=new File([blob],"tidelight-voice-note."+extension,{type:mime});setFiles(old=>[...old,file].slice(0,4));stream.getTracks().forEach(track=>track.stop());setRecording(false)};rec.start();setRecording(true)}catch(e){setRecording(false);setError(e instanceof Error?e.message:"Allow microphone access to record a voice note.")}}}>{recording?"■ Stop recording":"◉ Record voice note"}</button><span>Up to 4 files · images, video, PDF, audio</span></div><small className="community-watermark-note">Images receive a Tidelight research watermark. Media downloads stay available for 7 days.</small>
    {files.length?<div className="community-file-list">{files.map((file,index)=><div key={index}><span>{file.type.startsWith("audio/")?"◉":file.type==="application/pdf"?"PDF":file.type.startsWith("video/")?"▷":"▧"} {file.name} · {(file.size/1048576).toFixed(1)} MB</span><button type="button" onClick={()=>setFiles(old=>old.filter((_,i)=>i!==index))} aria-label={"Remove "+file.name}>×</button></div>)}</div>:null}
    <div className="community-composer-foot"><span>{body.length}/1,800 · Keep claims traceable to sources.</span><button className="community-primary" disabled={busy||(!body.trim()&&!files.length)}>{busy?"Uploading & publishing…":replyTo?"Reply to thread":"Post research note"}</button></div>
   </form>:null}
   <div className="community-feed-head"><div><span className="eyebrow small-eyebrow">THE DESK FEED</span><h2>Research in conversation</h2></div><div className="community-tabs"><button className={tab==="for-you"?"active":""} onClick={()=>setTab("for-you")}>For your desk</button><button className={tab==="latest"?"active":""} onClick={()=>setTab("latest")}>Latest</button></div></div>
   {tab==="for-you"&&profile?<p className="community-personal-note">Ranked using your watchlist, recent research, Strategy Lab runs, and reactions.</p>:null}
   {sorted.length?sorted.map(post=><article className="community-post" key={post.id}><div className="community-post-head"><div className="community-avatar">{post.author?.avatar_url?<img src={post.author.avatar_url} alt=""/>:(post.author?.display_name??"T").slice(0,1)}</div><div className="community-author"><Link href={"/community/"+encodeURIComponent(post.author?.handle??"")}><b>{post.author?.display_name??"Tidelight member"}</b></Link><small><Link href={"/community/"+encodeURIComponent(post.author?.handle??"")}>@{post.author?.handle}</Link> · {new Date(post.created_at).toLocaleString()}</small></div>{post.symbol?<span className="community-symbol">{post.symbol}</span>:null}</div>
    {post.reason&&tab==="for-you"?<div className="community-reason">✳ {post.reason}</div>:null}<div className="community-post-copy"><span className={"community-stance "+post.stance}>{post.stance==="bullish"?"POSITIVE CASE":post.stance==="bearish"?"RISK CASE":post.stance.toUpperCase()}</span><p>{post.body}</p>{post.source_url?<a className="community-evidence" href={post.source_url} target="_blank" rel="noreferrer">Evidence link ↗</a>:null}</div>
    {post.media?.length?<div className="community-media-grid">{post.media.map((item,index)=><div className={"community-media-item "+item.kind} key={item.url+index}>{item.kind==="image"?<a href={item.url} target="_blank" rel="noreferrer"><img src={item.url} alt={item.name}/></a>:item.kind==="video"?<video controls preload="metadata" src={item.url}/>:item.kind==="audio"?<div><b>◉ Voice / audio note</b><audio controls preload="metadata" src={item.url}/></div>:<a className="community-pdf" href={item.url} target="_blank" rel="noreferrer"><span>PDF</span><b>{item.name}</b><small>Open document ↗</small></a>}</div>)}</div>:null}
    {post.quoted?<div className="community-quote-preview"><b>@{post.quoted.author?.handle} · {post.quoted.symbol??"Research note"}</b><p>{post.quoted.body}</p></div>:null}
    <div className="community-actions"><button className={post.liked?"is-liked":""} onClick={()=>void react(post,"like")} aria-pressed={post.liked}><span>♥</span> Like <small>{post.likes}</small></button><button className={post.saved?"is-saved":""} onClick={()=>void toggleBookmark(post)} aria-pressed={post.saved}><span>▣</span> {post.saved?"Saved":"Save"}</button><button className={post.reposted?"is-reposted":""} onClick={()=>void react(post,"repost")} aria-pressed={post.reposted}><span>↻</span> Repost <small>{post.reposts}</small></button><button onClick={()=>{setQuote(post);setReplyTo(null);window.scrollTo({top:0,behavior:"smooth"})}}><span>❞</span> Quote</button><button onClick={()=>void openThread(post)}><span>↳</span> Reply <small>{post.replies}</small></button><button onClick={()=>{setHandle(post.author.handle);window.scrollTo({top:0,behavior:"smooth"})}}>Message</button><details className="community-more-actions"><summary aria-label="More actions">•••</summary><div><button onClick={()=>void moderate(post,"report")}>Report</button><button onClick={()=>void moderate(post,"block")}>Mute member</button></div></details></div>
   </article>):<div className="community-empty"><span>✳</span><b>The desk is quiet for now.</b><p>Start with a source-backed note on a listed US issuer or a Reality rToken. Your activity will shape the feed over time.</p></div>}
   {replyTo?<section className="community-thread"><div className="community-thread-head"><div><span className="eyebrow small-eyebrow">RESEARCH THREAD</span><h3>Keep the discussion attached to its evidence.</h3></div><button onClick={()=>{setReplyTo(null);setThread([])}}>Close</button></div>{thread.map(item=><article className="community-reply" key={item.id}><b>{item.author.display_name} <small>@{item.author.handle}</small></b><p>{item.body}</p>{item.source_url?<a href={item.source_url} target="_blank" rel="noreferrer">Source ↗</a>:null}{item.media?.length?<div className="community-media-grid">{item.media.map((media,index)=><div className={"community-media-item "+media.kind} key={media.url+index}>{media.kind==="image"?<a href={media.url} target="_blank" rel="noreferrer"><img src={media.url} alt={media.name}/></a>:media.kind==="video"?<video controls preload="metadata" src={media.url}/>:media.kind==="audio"?<audio controls preload="metadata" src={media.url}/>:<a className="community-pdf" href={media.url} target="_blank" rel="noreferrer"><span>PDF</span><b>{media.name}</b><small>Open document ↗</small></a>}</div>)}</div>:null}<button className={"community-comment-like"+(item.liked?" is-liked":"")} onClick={()=>void react(item,"like")} aria-pressed={item.liked}>♥ Like · {item.likes}</button></article>)}</section>:null}
  </section>
  <aside className="community-aside"><section className="community-profile-tools"><span className="eyebrow small-eyebrow">TIDELIGHT PEOPLE</span><h3>Find a research voice.</h3><form className="community-profile-search" onSubmit={event=>{event.preventDefault();const target=profileSearch.trim().replace(/^@/,"");if(target)location.href="/community/"+encodeURIComponent(target)}}><input value={profileSearch} onChange={event=>setProfileSearch(event.target.value)} placeholder="@username" aria-label="Search community username" required/><button className="community-primary">View profile ↗</button></form>{profile?<Link href={"/community/"+encodeURIComponent(profile.handle)}>Open your profile ↗</Link>:null}</section><section><span className="eyebrow small-eyebrow">YOUR SIGNAL GRAPH</span><h3>Built around what you follow.</h3><p>Notes linked to issuer events, SEC filings, and Reality pairs surface closer to the top as you research and react.</p><div className="community-signal-list"><span>01 <b>Watchlist focus</b></span><span>02 <b>Research trail</b></span><span>03 <b>Helpful reactions</b></span><span>04 <b>Fresh evidence</b></span></div><Link href="/watchlist">Tune your watchlist ↗</Link></section>
  <section className="community-inbox"><span className="eyebrow small-eyebrow">PRIVATE DESK NOTES</span><h3>Message a member</h3><p>Use a public Tidelight handle. Conversations are visible only to their participants.</p><form onSubmit={e=>{e.preventDefault();void openMessages()}}><input value={handle} onChange={e=>setHandle(e.target.value)} placeholder="@handle"/><button className="community-primary">Open inbox</button></form>{peerName?<div className="community-message-thread"><b>{peerName}</b><div className="community-messages">{messages.map(m=><p className={m.sender_id===userId?"mine":""} key={m.id}>{m.body}</p>)}</div><form onSubmit={e=>void sendMessage(e)}><textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} placeholder="Write a private desk note…" required/><button className="community-primary">Send message</button></form></div>:null}</section>
  <section className="community-safety"><span className="eyebrow small-eyebrow">COMMUNITY STANDARD</span><p>Separate issuer facts from token-market claims. Be clear about uncertainty. No trade calls, promotion spam, or unsupported claims.</p><small>Messages are limited to conversation participants; public notes stay readable to guests.</small></section>
  </aside></div>
 </main>
}